- q2_feature_table/__init__.py
- q2_feature_table/_summarize.py
- q2_feature_table/plugin_setup.py
- setup.py
This contains figures, tables, and summary statistics that are useful for learning about what information is in a ``FeatureTable``. This was in part designed to illustrate how different types of information could be combined into a single ``Visualization``. Here's some content from the ``index.html`` file:
> ENH: adds a summarize visualization

- q2_feature_table/_filter.py
- q2_feature_table/_transform.py
> ENH: In-place biom table operations

- q2_feature_table/_summarize.py
- q2_feature_table/assets/sample-count-detail.template
- q2_feature_table/assets/summarize.template
> ENH: Rebrand summarize viz

- .travis.yml
- q2_feature_table/_summarize/_visualizer.py
- q2_feature_table/_summarize/summarize_assets/index.html
- setup.py
fixes #41
fixes #39
fixes #32
fixes #23
partially fixes #40 
Some example visualizations:
* [empty table](https://view.qiime2.org/?f=https://dl.dropboxusercontent.com/u/2868868/temp/empty-table.qzv)
* [one sample table](https://view.qiime2.org/?f=https://dl.dropboxusercontent.com/u/2868868/temp/one-sample-table.qzv)
* [moving pictures tutorial table](https://view.qiime2.org/?f=https://dl.dropboxusercontent.com/u/2868868/temp/table.qzv)
> ENH: various improvements to summarize

- q2_feature_table/_normalize.py
- q2_feature_table/_summarize/_visualizer.py
- q2_feature_table/_summarize/summarize_assets/index.html
- q2_feature_table/_summarize/summarize_assets/sample-frequency-detail.html
- q2_feature_table/plugin_setup.py
...for consistency with type nomenclature.
fixes #40
> ENH: count(s) replaced with frequency(ies)

- q2_feature_table/_summarize/_visualizer.py
- q2_feature_table/plugin_setup.py
Avoids cast to dense (per vector) and operates directly on the contained sparse matrix
> Use Table.sum

- q2_feature_table/_summarize/_visualizer.py
- q2_feature_table/_summarize/tabulate_seqs_assets/index.html
> ENH: Add download link to raw FASTA file

- q2_feature_table/plugin_setup.py
> BUG: Update table filter tutorial URL

- q2_feature_table/_summarize/_visualizer.py
Note: I confirmed that this issue doesn't come up with the IQR feature frequency is zero.
> BUG: handle boundary case of IQR sample frequency of zero

- q2_feature_table/plugin_setup.py
This PR adds a `description` and `short_description` to `q2-feature-table`.  When used with my branch of `q2cli`, you get the following output:
````SHELL
(qiime2-dev) ➜  ~ qiime --help q2-feature-table
Usage: qiime [OPTIONS] COMMAND [ARGS]...
QIIME 2 command-line interface (q2cli)
--------------------------------------
To get help with QIIME 2, visit https://qiime2.org.
To enable tab completion in Bash, run the following command or add it to
your .bashrc/.bash_profile:
source tab-qiime
To enable tab completion in ZSH, run the following commands or add them to
your .zshrc:
autoload bashcompinit && bashcompinit && source tab-qiime
Options:
--version  Show the version and exit.
--help     Show this message and exit.
Commands:
info           Display information about current deployment.
tools …
```
> Description feature

- .travis.yml
- ci/environment.yaml
- ci/recipe/meta.yaml
- setup.py
Pair programmed with @jairideout & @ebolyen
> CI: Travis uses environment.yaml

- q2_feature_table/_summarize/_visualizer.py
> ENH: Add qualitative counts to feature summary

- q2_feature_table/_filter.py
- q2_feature_table/plugin_setup.py
- q2_feature_table/tests/test_filter.py
All other plugins that I checked refer to this as "metadata" not
"sample_metadata".
--------
~~Would like to let the tests run in Travis.~~
> ENH: Change sample_metadata to metadata

- q2_feature_table/_core_features/_visualizer.py
- q2_feature_table/_summarize/_visualizer.py
Depends on https://github.com/qiime2/q2templates/pull/25
> MAINT: update to use `q2templates.df_to_html`

- q2_feature_table/_summarize/_visualizer.py
> BUG: Add y-axis labels to `summarize` plots

- q2_feature_table/__init__.py
- q2_feature_table/_heatmap/__init__.py
- q2_feature_table/_heatmap/_visualizer.py
- q2_feature_table/_heatmap/assets/index.html
- q2_feature_table/plugin_setup.py
- q2_feature_table/tests/test_heatmap.py
- setup.py
This is a simple first-cut at heatmap visualization, sans interactivity.
Fixes #36
> ENH: Visualize feature table with a heatmap

- q2_feature_table/_merge.py
- q2_feature_table/tests/test_merge.py
> ENH: Support merging on overlapping axes (sum)

- q2_feature_table/_summarize/summarize_assets/sample-frequency-detail.html
- q2_feature_table/_summarize/summarize_assets/src/controls.js
I modified the sample-frequency-detail.html file and made the slider-value have a minimum of 0.  I also modified the controls.js and made the sliderValue = 0 if the sliderValue is changed to a negative number. 
Fixes #125
> Prevent Negative Slider Value

- q2_feature_table/__init__.py
- q2_feature_table/_merge.py
- q2_feature_table/plugin_setup.py
- q2_feature_table/tests/test_merge.py
> ENH: merge methods are now variadic

- q2_feature_table/_filter.py
- q2_feature_table/plugin_setup.py
- q2_feature_table/tests/filter/test_filter_sequences.py
> ENH: filter-seqs supports table-based filtering

- q2_feature_table/_filter.py
- q2_feature_table/_group.py
- q2_feature_table/_heatmap/_visualizer.py
- q2_feature_table/_summarize/_visualizer.py
- q2_feature_table/plugin_setup.py
- q2_feature_table/tests/filter/test_filter_features.py
- q2_feature_table/tests/filter/test_filter_samples.py
- q2_feature_table/tests/filter/test_filter_sequences.py
- q2_feature_table/tests/test_group.py
- q2_feature_table/tests/test_heatmap.py
- q2_feature_table/tests/test_summarize.py
See qiime2/qiime2#359 for details.
> MAINT: new Metadata updates

- q2_feature_table/citations.bib
- q2_feature_table/plugin_setup.py
- setup.py
> DOC: add citations

- q2_feature_table/citations.bib
lost this in a vim register :(
> DOC: missing author

- q2_feature_table/_core_features/_visualizer.py
- q2_feature_table/_filter.py
- q2_feature_table/_heatmap/_visualizer.py
- q2_feature_table/_merge.py
- q2_feature_table/_summarize/_visualizer.py
- versioneer.py
Numerous minor updates for compliance with flake8 v3.6, as discussed in qiime2/qiime2#415
Note: flake8 has been disabled in versioneer.py.
> Update for flake8 v3.6

- q2_feature_table/_normalize.py
- q2_feature_table/plugin_setup.py
- q2_feature_table/tests/test_normalize.py
Adds an option to perform rarefaction with replacement by multinomial sampling.
> ENH: add rarefy with replacement

- q2_feature_table/__init__.py
- q2_feature_table/_transform.py
- q2_feature_table/plugin_setup.py
- q2_feature_table/tests/test_transform.py
This method allows for transposing rows and columns in a feature table. 
Fixes #195
> ENH: Exposes new transpose method

- q2_feature_table/_merge.py
- q2_feature_table/tests/test_merge.py
> merge_taxa supports dataframes

- ci/recipe/meta.yaml
- q2_feature_table/_core_features/_visualizer.py
- q2_feature_table/_core_features/core_features_assets/index.html
- q2_feature_table/tests/test_core_features.py
Co-authored-by: Andrew Sanchez <inbox.asanchez@gmail.com>
> DEP: Seaborn 0.10 changes

- q2_feature_table/plugin_setup.py
`FeatureData[AlignedSequence]` can now be passed to `filter-seqs`, in which case `FeatureData[AlignedSequence]` will be the output.
Addresses #232.
> IMP: generalizes filter-seqs

- q2_feature_table/_summarize/_vega_spec.py
Fixes #224 
---
```python
import qiime2
import pandas as pd
from qiime2.plugins import feature_table as ft_plugin
table_data = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
index=['s1', 's2', 's3'],
columns=['f1', 'f2', 'f3'])
md_data = pd.DataFrame([["Yes", "No"], ["No", "Yes"], ["Yes", "No"]],
index=pd.Index(['s1', 's2', 's3'], name='id'),
columns=["foo", "bar"])
table = qiime2.Artifact.import_data('FeatureTable[Frequency]',
table_data, view_type=pd.DataFrame)
md = qiime2.Metadata(md_data)
viz, = ft_plugin.visualizers.summarize(table, md)
viz.save('mwe.qzv')
```
> BUG: summarize - sync updates

- q2_feature_table/examples.py
> Use init_data_collection

- q2_feature_table/_merge.py
- q2_feature_table/plugin_setup.py
- q2_feature_table/tests/test_merge.py
Added an `average` `overlap_method` to `merge`.
Enabled `merge` to process `RelativeFrequency` `FeatureTable`s.
> ENH: added average and RelativeFrequency handling to merge

- q2_feature_table/_summarize/_vega_spec.py
- q2_feature_table/tests/test_summarize.py
> [BACKPORT] BUG: fix handling of NaNs in feature-table summarize

- q2_feature_table/_core_features/core_features_assets/index.html
- q2_feature_table/_summarize/summarize_assets/sample-frequency-detail.html
- q2_feature_table/tests/test_core_features.py
> Updated the "Feature Count" and renamed it as "Frequency". 

- q2_feature_table/__init__.py
- q2_feature_table/_split.py
- q2_feature_table/plugin_setup.py
- q2_feature_table/tests/test_split.py
> NEW: adds feature-table split method
