qiime2/q2-feature-table

.travis.yml
LICENSE
q2_feature_table/__init__.py
q2_feature_table/_filter.py
q2_feature_table/_merge.py
q2_feature_table/_normalize.py
q2_feature_table/_summarize/__init__.py
q2_feature_table/_summarize/_visualizer.py
q2_feature_table/_transform.py
q2_feature_table/plugin_setup.py
q2_feature_table/tests/__init__.py
q2_feature_table/tests/test_filter.py
q2_feature_table/tests/test_merge.py
q2_feature_table/tests/test_normalize.py
q2_feature_table/tests/test_summarize.py
q2_feature_table/tests/test_transform.py
setup.py

New date-based versioning scheme is:
- YYYY.M.patch.dev0 for development version (e.g. 2017.2.0.dev0, 2017.2.1.dev0, 2018.10.0.dev0)
- YYYY.M.patch for release version (e.g. 2017.2.0, 2017.2.1, 2018.10.0)
Plugins/interfaces are recommended to specify `qiime2 == YYYY.M.*` in setup.py's `install_requires` to obtain patch releases for a given train release.
The new versioning scheme is PEP 440 compliant.

ENH: new date-based versioning; `qiime` -> `qiime2` package rename

---

q2_feature_table/_summarize/_visualizer.py
q2_feature_table/_summarize/summarize_assets/feature-frequency-detail.html
q2_feature_table/_summarize/summarize_assets/index.html

- ~interactive exploration of rarefaction depth, as we had in q2d2. this would be really helpful to integrate with metadata, so you can determine how many samples of each metadata type a specific depth would filter from your data set~
- ~some users at the iceland workshop noted that it would be useful to know the taxonomic composition of the samples when they're choosing their even sampling depth based on the `summarize` output - this should be possible, but would require optional artifacts and would have some overlap with the existing taxa plots (so this is lower priority)~
Resolves #24

Multi-commit Summarize Improvements

---

q2_feature_table/_summarize/_visualizer.py

As of numpy 1.12.0 using floats with `np.zeros` has been removed, which caused our bins value to break `sns.distplot`, because `round` returned a float.

BUG: Bin number type issue with seaborn or numpy

---

q2_feature_table/plugin_setup.py

URLs are changing quite a bit between QIIME 2 releases. It's better to link to the docs site and describe what tutorial users need to look for, instead of having a broken link in the software that requires a patch release to fix. We can re-introduce specific URLs to the software when URLs are more stable/predictable.

MAINT: remove filtering tutorial url from help text

---

.travis.yml
README.md

* Adds test coverage reporting (see [here](https://coveralls.io/builds/10282745/source?filename=q2_feature_table%2F_summarize%2F_visualizer.py), for example). 
* Swaps `py.test` for `nosetests` as the former integrates more easily with `Coverage.py`, and is a drop-in replacement for how we were using `nosetests`.
* Adds coveralls badge to `README.md`. 
This PR serves as a proposal for how I'll update the other QIIME2 repos to include coverage reporting. Once we're good with how this is happening, I'll start working on other PRs.

TST: adds coverage testing and reporting to Travis CI

---

q2_feature_table/_normalize.py
q2_feature_table/tests/test_normalize.py

ENH: Clarify error message when table is rarefied to nothing

---

q2_feature_table/tests/test_filter.py

Necessary for changes in https://github.com/qiime2/qiime2/pull/277

MAINT: avoid empty Metadata in unit tests

---

q2_feature_table/_filter.py
q2_feature_table/plugin_setup.py
q2_feature_table/tests/test_filter.py

This PR addresses Issue #101 .
I've added an optional `exclude_ids` flag to `filter_features` and `filter_samples`.  I declared the new flag in the plugin setup and added unit tests.
This flag is set to `False` by default.  If it is specified as true, then the filter function in question returns the inverse of what it would otherwise return.  For example:
````PYTHON
df = pd.DataFrame({'SequencedGenome': ['yes']},
index=['O1'])
metadata = qiime2.Metadata(df)
table = Table(np.array([[0, 1, 3], [1, 1, 2]]),
['O1', 'O2'],
['S1', 'S2', 'S3'])
filter_features(table, metadata=metadata)
````
... returns:
````BASH
#OTU ID	S2	S3
O1	1.0	3.0
````
This makes sense: we asked for the stuff in `index=['01']`, and we got it.
In comparison, if we set `exclude_ids=True`, we get:
````PYTHON …
```

ENH: Optional flag for exclusion filters, Fixes #101

---

q2_feature_table/plugin_setup.py

After addressing qiime2/q2-diversity#110, this property is no longer used in QIIME 2.

MAINT: remove uniform-sampling effort property

---

q2_feature_table/__init__.py
q2_feature_table/_core_features/__init__.py
q2_feature_table/_core_features/_visualizer.py
q2_feature_table/_core_features/core_features_assets/index.html
q2_feature_table/plugin_setup.py
q2_feature_table/tests/test_core_features.py
setup.py

Example .qzv: [core-features.qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fforum-qiime2-org.s3-us-west-2.amazonaws.com%2Foriginal%2F1X%2F89efca24e973aa4b164cddc9ce31360ddea942de.qzv)
Ported @gregcaporaso's code from https://github.com/qiime2/q2-diversity/pull/127 and made the following changes:
- All references to "core microbiome" are now "core features".
- Removed metadata-based filtering support from the viz in favor of using `filter-samples` or `filter-features`.
- Refactored unit tests to reduce code duplication, and added several new tests.
- Fixed a precision bug where small enough step sizes could cause "feature list" .tsv output files to be overwritten.
- Fixed a bug where HTML table contents could have been truncated.
- Better handling of the case where …

ENH: add `core-features` visualizer

---

q2_feature_table/_summarize/tabulate_seqs_assets/index.html

Works in `qiime tools view` (causes the download dialog to fire). 
q2view opens a new tab, but we can probably teach it what a `.fasta` file is to avoid that

BUG: replace download attr for tabulate-seqs

---

q2_feature_table/__init__.py
q2_feature_table/_group.py
q2_feature_table/plugin_setup.py
q2_feature_table/tests/test_group.py

This allows you to group a feature-table using a metadata category which
maps existing ids into new bins. This can be done on either axis of the
table.
fixes #86

ENH: adds group method

---

q2_feature_table/plugin_setup.py

Sets an integer `Range` on sampling depth. I was not sure if and how to add a unit test for this as I believe this is controlled at plugin method registration. Below is the output I receive now:
```bash
(qiime2-2017.8) $ qiime feature-table rarefy --i-table table.qza --o-rarefied-table test --p-sampling-depth 5
Saved FeatureTable[Frequency] to: test.qza
(qiime2-2017.8.redux) $ qiime feature-table rarefy --i-table table.qza --o-rarefied-table test --p-sampling-depth 0
Usage: qiime feature-table rarefy [OPTIONS]
Error: Invalid value for "--p-sampling-depth": 0 is smaller than the minimum valid value 1.
(qiime2-2017.8.redux) $ qiime feature-table rarefy --i-table table.qza --o-rarefied-table test --p-sampling-depth -1
Usage: qiime feature-table rarefy [OPTIONS]
Error: Invalid value for …
```

Fixes #129

---

ci/recipe/meta.yaml

As of this commit, this repository does not explicitly require 2.1.6.
However, we are issuing this minimum version change as to implicitly
take advantage of the bug fixes, performance improvements, and to expose
API expansions (which may trigger refactors).

BLD: set the minimum BIOM version 2.1.6.

---

q2_feature_table/_summarize/_visualizer.py

Fixes #122 
On a test table with 65k features, this brought the runtime down to ~25 seconds, from ~35 minutes previously. The bottleneck appears to be matplotlib's rendering of the rugplot, so by disabling, we get a bit of performance gain more or less for free. The data is still available as a delimited download in the viz, so if users are interested in more complex figures, they have the data available to make it happen!

BUG: Disable feature freq. rugplot

---

q2_feature_table/_merge.py
q2_feature_table/tests/test_merge.py

Modifies `q2_feature_table.merge` to prefer the use of `Table.concat` which is 1-2 orders magnitude faster than `Table.merge` with increasing performance gains as the number of tables to merge gets large.

PERF: prefer Table.concat over Table.merge

---

ci/recipe/meta.yaml

This PR changes the minimum required version of `biom` to accomodate another PR which will add a `with_replacement` option to the `rarefy` function.

update biom version req. to 2.1.7

---

q2_feature_table/_heatmap/_visualizer.py
q2_feature_table/plugin_setup.py
q2_feature_table/tests/test_heatmap.py

Fixes #173 
Updates: _heatmap options for clustering, options and docs for plugin, unit test for feature
---
Sample output with no clustering (`none` option).

allow heatmap to not cluster on samples or features

---

q2_feature_table/_heatmap/_visualizer.py
q2_feature_table/plugin_setup.py
q2_feature_table/tests/test_heatmap.py

This will allow heatmaps to be labeled with feature metadata (e.g., taxonomy).
Contrast with taxa collapse: this will display individual ASVs annotated with whatever feature metadata you choose. So taxa are not collapsed.

annotate heatmap with feature metadata (e.g., taxonomy)

---

q2_feature_table/examples.py
q2_feature_table/plugin_setup.py
q2_feature_table/tests/test_examples.py
q2_feature_table/tests/test_merge.py

This PR adds two usage examples to this plugin:
1. The first is a merge example of two feature tables. The `UsageInput` accepts a list of tables to accomplish this action.
2. The second is a merge example of three feature tables. This example will accept an additional parameter `overlap_method='sum'`. Currently, the validation for `UsageInput` will not accept this parameter, so changes will be needed before merging.
The plugin setup was changed to accept the new functions that create the usage examples. More changes for plugin setup might be needed as more usage examples are added.
---
Blocked by https://github.com/qiime2/qiime2/pull/528

ENH: Added usage examples

---

q2_feature_table/_summarize/_visualizer.py

Adding a limit of [50 bins](https://github.com/mwaskom/seaborn/blob/09f5746ff214029ff068204a1d781c6ff7a3b25a/seaborn/distributions.py#L2625) for seaborn.histplot to reduce the amount of memory used. Using 50 bins as this is the upper limit in the previous method used seaborn.distplot.
Usage before this change:
```
$ /usr/bin/time -v conda run -n qiime2-2021.4 qiime feature-table summarize --i-table /qmounts/qiita_data/working_dir/8373aeae-05a8-47a0-98af-145753259715/test-species.qza --o-visualization /qmounts/qiita_data/working_dir/8373aeae-05a8-47a0-98af-145753259715/qiime2-2021.4.qzv
Saved Visualization to: /qmounts/qiita_data/working_dir/8373aeae-05a8-47a0-98af-145753259715/qiime2-2021.4.qzv
Command being timed: "conda run -n qiime2-2021.4 qiime feature-table summarize --i-table …
```

limiting the number of bins for seaborn.histplot

---

ci/recipe/meta.yaml

This PR pins matplotlib to version 3.6.0 due to a [reported bug in seaborn](https://github.com/mwaskom/seaborn/issues/3072) (dep in q2-feature-table) caused from matplotlib version 3.6.1 that resulted in [build failures to our 2022.11 crons](https://github.com/qiime2/package-integration/actions/runs/3272779670) for the community distribution. As mentioned in the seaborn issue, the bug should be resolved with the new 3.7.0 build of matplotlib, and this pin will be removed at that time.

pin: matplotlib 3.6.0

---

q2_feature_table/_normalize.py
q2_feature_table/plugin_setup.py
q2_feature_table/tests/test_normalize.py

Rarefy `with_replacement=True` was incorrectly retaining samples with depth below the requested subsampling level. This behavior differed from `with_replacement=False`, where samples below depth are removed from the table. This Pull Request corrects the behavior of `with_replacement=True` by removing samples below the requested depth prior to subsampling.

Rarefy with replacement bug

---

q2_feature_table/_examples.py
q2_feature_table/plugin_setup.py

This PR adds usage examples for the following methods within q2-feature-table:
```
summarize
tabulate-seqs
```
In addition, I've done some minor clean-up to the existing examples to keep formatting consistent and reduce the number of separate imports happening within `plugin_setup.py`.

ex: adds summarize/tabulate-seqs & some misc cleanup

---

q2_feature_table/_examples.py

updating usage example URLs that are dynamically generated to static usage-specific URLs so that it doesn't fail with each new dev bump

bug: fix dynamic URL causing usage example failure

---

q2_feature_table/plugin_setup.py

This PR adds functionality to q2-feature-table transpose that allows any feature table type (Frequency, RelativeFrequency, PresenceAbsence, Composition) in and returns the same feature table type. 
This fixes issue https://github.com/qiime2/q2-feature-table/issues/272.

MAINT: adds typematching functionality for feature-table transpose
